# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e0dea48eb17a8c4c9c4707797b3c161fdaacb4b33443069118ad6fcbf316ff6db21dc264298827d9ecaf1e884d9cd5df0045cb1f192ed5ed5053a2edec5ba11

test:
  secret_key_base: 2858c9819f31fe3487e9a7ab1ac1e9913eae40e7d515c9830cfecbd4ffa4d728d211e377feaae362f7354b7536404f3c221f75be646148cfac6817ab61053c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
